---
abstract: 'identifying mutational significance in cancer genomes.'
author:
  - 'Beifang Niu && Cyriac Kandoth from The Genome Institute of Washington University at St. Louis'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.120351'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MuSiC2
version: 0.1
